# Generated by Django 2.2.2 on 2019-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='skills',
            field=models.CharField(blank=True, choices=[('FE', 'Front-end'), ('BE', 'Back-end'), ('FS', 'Full-Stack'), ('IT', 'IT-Specialist')], max_length=2),
        ),
    ]
