# Generated by Django 2.2.2 on 2019-08-28 22:49

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190810_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
