# Generated by Django 2.2.2 on 2020-07-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tutorial_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='url',
            new_name='urls',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='skills',
        ),
        migrations.AddField(
            model_name='instructor',
            name='skills',
            field=models.ManyToManyField(to='courses.Skill'),
        ),
    ]
