# Generated by Django 2.2.2 on 2019-10-25 23:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191026_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
